// ── Updated by /cofounder skill at session end ────────────────────────────────

export const ROADMAP = {
  lastUpdated: 'August 26, 2026',

  content: {
    totalAyahs: 6236,
    doneAyahs: 6236,
    queuePosition: 'COVERAGE COMPLETE — all 6,236 ayahs covered. Validation: 2,235 validated / 777 pending. Aug 8 (a): the CLAIM axis is clean — zero corpus-refuted claims across all 4,398 files, after the last five word-count defects were closed and verify_claims itself was fixed twice (~84% false positives on one detector, 98% unactionable output on another). Reviewer load cut 5,682 → 2,549 entries. Aug 8 (b): the first calibration batch of the adversarial READ came back 20/20 defective — the sweep-clean axis and the read axis are measuring different things, and the read is the one that catches false theses. All 16 written verdicts are now worked: 11 REPAIRED in place (each defect re-verified against the paired tafsir report and the corpus cache before the edit went in) and 5 QUARANTINED for regeneration with `rebuild_required: true` + an in-file banner, because their central thesis is refuted and a patch would make a broken file read finished.',
    surahsInProgress: 114,
  },

  unlockChain: [
    {
      id: 'corpus',
      label: 'Tadabbur corpus',
      sub: '3,018 files · 100% ayah coverage · 2,158 validated — the moat',
      why: 'Every other layer is built on top of this. Coverage is COMPLETE (all 6,236 ayahs, verified Jul 12); validation triage (Jul 12) found 0 defects — the 844 pending files split into 272 auto-verified (awaiting the interpretive tafsir read) and 566 awaiting enrichment. NOT a web-publishing asset (decision Jul 7): it is the grounding corpus for AI surfaces.',
      status: 'active' as const,
      current: 'validation burn-down is THE bottleneck: 777 files still validated:false — and the Aug 8 calibration read reset what that number means. 20 of 20 sampled files were defective, so the burn-down is NOT "read 777 files and flip the clean ones"; there are no clean ones. The real question is which files are worth repairing vs regenerating, and 5 of the first 16 already answered regenerate. Throughput on the read is now the bottleneck, not the sweep. NOTE: "enrichment gated on the tafsir re-key" is RETIRED — the re-key shipped Aug 6 (scripts/rekey_tafsir.py, content-verified, 1,810 passages / 4,561 ayahs indexed) and enrichment has been running since: 930 files enriched, 294 left in scripts/enrich-queue-v2.json.',
      blockedBy: null,
    },
    {
      id: 'meaning-layer',
      label: 'Graph substrate',
      sub: 'validated nodes + typed munāsabāt edges',
      why: 'THE current priority (decision Jul 7: "graph connections made to make future stuff easier"). Substrate hardened Jul 12-13: freshness gate (npm run graph / graph:check), provenance-preserving promotion overlay, motif-level review. Discovery runs 1+2 complete: 643 root-motifs reviewed, +669 confirmed cross-surah edges each carrying a quotable basis. Graph now 13,279 traversable edges; validated-only view 7,320.',
      status: 'active' as const,
      current: 'validated-only view 7,691 edges (was 7,438); graph 13,287 traversable across 3,008 nodes. Rebuilt Aug 8 after the content repairs made the projection stale. Next lever unchanged and now unblocked: burn down the 777 unvalidated files — every flip adds edges to this view, and this view is what the AI surface waits on. 350-elite promotion queue still untouched.',
      blockedBy: null,
    },
    {
      id: 'ai-surface',
      label: 'AI exposure surface',
      sub: 'typing or voice companion over the substrate',
      why: 'Decision Jul 7: corpus gets exposed through AI surfaces ("voice AI or even typing AI as needed"), NOT web ayah pages. Text-first companion is the cheap demand test before any voice build.',
      status: 'queued' as const,
      current: 'Not started — waits on substrate',
      blockedBy: 'graph substrate (validation burn-down + promoted edges)',
    },
    {
      id: 'voice',
      label: 'Voice companion',
      sub: 'one pathway, built LAST',
      why: 'Single-ayah depth-first, Claude-as-constrained-brain (STT→Claude→TTS). One pathway over the substrate, not the product. Demand unproven (advisor flag) — build after a typing surface proves the interaction.',
      status: 'later' as const,
      current: 'Not started',
      blockedBy: 'typing surface + demand signal',
    },
  ],

  visionLayers: [
    { num: 1, label: 'Living map of Quranic meaning', status: 'building' as const },
    { num: 2, label: 'Personal reflection layer', status: 'shipped' as const },
    { num: 3, label: 'Contemplation companion (AI)', status: 'later' as const },
  ],

  openQuestions: [
    'Which AI surface first — typing companion or voice — and what triggers the build? (NORTH-STAR open item)',
    'FULLY ANSWERED — interpretive-read workflow running since Jul 31 (rubric + parallel reviewers + audit log; 0 false theses), and the tafsir re-key, which was the open half, SHIPPED Aug 6. Enrichment is no longer gated: 930 files enriched, 294 queued. Nothing here is waiting on Azam.',
    'The 26 flagged files all share one defect: a classical ikhtilaf stated in one voice. One exemplar paragraph is drafted (9:4-6) awaiting a yes/no on the shape before the pattern is repeated. Aug 8 sharpened this: the SAME defect appeared in 4 of the 16 calibration verdicts (27:8 "camera angles" over Tabari\'s explicit واختلف أهل التأويل; 23:50 al-Ramla struck by name; 29:22 Tabari\'s اصحّ عندي; 21:44 ومخالفيه). The repairs now name the dispute and its winner — if that shape is right, it is the template for all 26.',
    'word_count means two different things across the corpus — some files hold the AYAH word count, some the reflection\'s essay count. Both conventions appear among the 16 files touched Aug 8 (21:44 = 5,513 essay words; 22:66 = 10 ayah words). Each file is now internally consistent, but the corpus needs one convention picked and applied as a batch job. Not a per-file repair — do not spend a reader\'s attention on it.',
    'Definition of "substrate v1.0 done" — measurable gates so graph work has a finish line (deliberation F5); discovery below DF≤10 stays closed pending a phrase-level method.',
    'Do we collect user reflections? Unlocks longitudinal memory (the Blomma moat).',
    'Paths bet review 2026-09-25: do article/hub attribution strips (?src=) beat the old homepage baseline (9 visitors/60d)? If not, archive paths.',
    'Ayah reader route (/reflections): built 2026-07-31 against NORTH-STAR decision 4, then noindexed + pulled from nav and sitemap. Keep it as an unindexed path/hub destination, delete it, or reopen the decision? It also does not filter to validated nodes yet (decision 2).',
    'Monetization + scholar endorsements: who first, what the ask looks like.',
  ],

  shipped: [
    { title: 'Course 5 — Yūsuf: Nothing Was Wasted. Designed and built in one session through the course skill: the muḥsin refrain mapped as a 5-station spine (12:22/36/56/78/90, corpus-verified), kadhālika kidnā li-Yūsuf as the machinery-reversal, the 12:24 ikhtilāf with named holders, al-Laṭīf landed at 12:100 — the only self-biographical use in the Quran', date: 'Aug 2026' },
    { title: 'Course 4 — Ādam: We Wronged Ourselves. The pair with Iblīs is complete: the fork taught at the grammar level (fa-ghawā vs aghwaytanī, corpus-verified at the form level), the 20:121 ʿiṣma question faced with named scholars (al-Qurṭubī, Ibn Fūrak, al-Rāzī, al-Ālūsī), and the kalimāt dispute presented with al-Ṭabarī\'s ruling as his ruling', date: 'Aug 2026' },
    { title: 'Course 3 — Iblīs: The Refusal That Had a Reason. Six modules, built from the 14-edition tafsir reports rather than the reflections (a new substrate scanner showed 23 of 28 supporting files had never been interpretively read). Teaches the 18:50 angel/jinn ikhtilāf with named holders on both sides without resolving it', date: 'Aug 2026' },
    { title: 'Courses launched free: Dāwūd (The Return Inside the Crown) and Sulaymān (Am I Grateful or Ungrateful?) — 12 modules, every ayah verified against the Uthmani text, wired into the prophet hubs and /prophets with per-module progress', date: 'Aug 2026' },
    { title: 'Tafsir source coverage 4 → 14 editions: the 353 "fabricated citation" files were our own blind spot, not a content defect — flags 353 → 0, and not one file was fixed by editing a reflection', date: 'Aug 2026' },
    { title: 'validation_level stamped on all 3,031 reflections (read vs mechanical) — 2,235 said validated:true and zero had passed a read that can catch a wrong idea', date: 'Aug 2026' },
    { title: 'Two quarantined files rebuilt through the skill (30:49, 33:43); three remain', date: 'Aug 2026' },
    { title: 'Calibration-batch verdicts worked: 11 tadabburs repaired against their tafsir reports + corpus, 5 quarantined for regeneration with briefs (docs/rebuild-register-2026-08-08.md)', date: 'Aug 2026' },
    { title: 'Divine names cluster: 31 of 99 written (waves 1-5), each with an entity + hub; /names index live with all 99', date: 'Aug 2026' },
    { title: '/names counts audited and repaired: 9 of 99 were wrong (Al-Malik read 152 — 88 of those were malak, ANGEL). Three published articles carried the error. audit-divine-name-counts.mjs now verifies all 99 on demand', date: 'Aug 2026' },
    { title: 'Content category playbook written — Index/Entry/Depth layers, the 5-step overlap scan, the validator traps', date: 'Aug 2026' },
    { title: 'Interpretive-read gate: 50 files read, 24 activated, 0 false theses; 3 frontmatter Arabic defects + 16 script-corruption spots repaired', date: 'Jul 2026' },
    { title: 'Guided paths repaired: all 20 stops now land on real content (was 13)', date: 'Jul 2026' },
    { title: 'Hub synthesis backlog closed — 25 written; every hub with 3+ articles has a real overview', date: 'Jul 2026' },
    { title: '4 corpus-verified articles filling empty path hubs (tadabbur, tawakkul, khushu, nazm)', date: 'Jul 2026' },
    { title: 'Ayah records tagged into the graph: 398 tags, 35 -> 160 records connected, 4 -> 44 hubs', date: 'Jul 2026' },
    { title: 'Sitemap repair: articles were entirely omitted (Next Data-Cache froze the Supabase read)', date: 'Jul 2026' },
    { title: 'Landing redesign (advisor/persona-tested): content-forward hero, articles surfaced, honest paths band', date: 'Jul 2026' },
    { title: 'Paths distribution: /paths index + attribution strips on article/hub pages (instrumented)', date: 'Jul 2026' },
    { title: 'FAQ AEO layer: 36 Q&As across top-10 organic articles (FAQPage schema 1→11)', date: 'Jul 2026' },
    { title: 'Quranic economics article cluster (5 corpus-verified articles + Fable QA pass)', date: 'Jul 2026' },
    { title: 'Motif-level munāsabāt review: 643 roots, +669 confirmed edges with quotable bases', date: 'Jul 2026' },
    { title: 'Graph substrate hardening: freshness gate, provenance-preserving promotion, validation triage (0 defects)', date: 'Jul 2026' },
    { title: 'Corpus coverage COMPLETE — all 6,236 ayahs', date: 'Jul 2026' },
    { title: 'NORTH-STAR.md standing decisions + adversarial review (docs/)', date: 'Jul 2026' },
    { title: 'Graph node validation gate + edge discovery pass (77,827 proposals)', date: 'Jul 2026' },
    { title: 'Tadabbur corpus ~97% coverage (109 surahs, 801 tafsir reports)', date: 'Jun 2026' },
    { title: 'Semantic meaning-layer validated end-to-end (graph-lab)', date: 'Jun 2026' },
    { title: '114 surah overview pages', date: 'Mar 2026' },
    { title: 'Entity hub system (101 hubs, full audit)', date: 'Apr 2026' },
    { title: 'Auth + reading layer (history, favorites, notes)', date: 'Apr 2026' },
    { title: 'Institutional pages (about, methodology, contested-verses)', date: 'Apr 2026' },
    { title: 'AEO motion (answer-first + auto FAQPage schema)', date: 'Jun 2026' },
    { title: 'Guided Paths feature', date: 'Apr 2026' },
  ],
}
