/**
 * Batch 4c: Overhaul surahs 51-77
 * Run: npx tsx scripts/batch-visual-overhaul-4c.ts
 */
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const overhauls = [
  { surah_number: 51, why_this_surah: "Opens with four oaths by wind and movement — scattering, carrying, flowing, distributing. Then pivots: 'Indeed, what you are promised is true, and indeed, the recompense is going to occur.' The surah of certainty — moving from visible evidence (wind, rain, signs on earth) to the invisible truth (judgment, accountability).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 52, why_this_surah: "The surah of Mount Sinai (al-Ṭūr). Jubayr ibn Mut'im, a polytheist, came to Madinah and heard the Prophet ﷺ reciting it in Maghrib prayer. When he reached 'Or were they created by nothing, or were they the creators?' (52:35), he said: 'My heart nearly flew.' The verse that nearly converted him on the spot.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 53, why_this_surah: "The surah of the star (al-Najm) — containing the account of the Prophet's ﷺ ascension (Mi'raj), when he saw Jibril in his true form at Sidrat al-Muntaha, the boundary of the created world. 'The eye did not swerve, nor did it transgress' (53:17). The first surah in which the Prophet ﷺ prostrated publicly, and the polytheists prostrated with him.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 54, why_this_surah: "The surah of the moon (al-Qamar) — 'The Hour has drawn near, and the moon has split' (54:1). Records the miracle of the splitting of the moon. The surah's refrain — 'And We have certainly made the Quran easy to remember. So is there anyone who will remember?' — repeats four times, once after each destroyed nation's story.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 55, why_this_surah: "The surah of the refrain — 'So which of the favors of your Lord would you deny?' repeated thirty-one times. When the Prophet ﷺ recited it to his companions, they were silent. He said: 'The jinn responded better than you — every time I recited it, they said: None of Your favors do we deny, our Lord.' The Quran's most musical surah.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 56, why_this_surah: "The surah of the three groups: the foremost (sābiqūn), the companions of the right, and the companions of the left. The Prophet ﷺ said: 'Whoever recites Surah Al-Waqi'ah every night will never be afflicted with poverty.' The surah's description of the foremost — on thrones facing each other, served by immortal youth — is the Quran's most vivid paradise.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "Three Groups", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 57, why_this_surah: "The surah of iron (al-Ḥadīd) — 'And We sent down iron, wherein is great military might and benefits for the people' (57:25). The Quran says iron was 'sent down,' and modern science confirms meteoritic iron arrived from space. Opens with everything in the heavens and earth glorifying God, and closes with the light that runs before believers on the Day of Judgment.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 58, why_this_surah: "Opens with a woman arguing with the Prophet ﷺ about her husband — Khawla bint Tha'laba, whose husband declared ẓihār (an unjust pre-Islamic divorce formula). 'A'ishah said: 'Praised be God, whose hearing encompasses all things. I was in the room and could not hear everything she said, yet God heard her from above seven heavens.'", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 59, why_this_surah: "Contains the most concentrated passage of God's names in the entire Quran — the final three ayahs (59:22-24) list over a dozen divine names in rapid succession: the Knower of the unseen, the King, the Holy, the Source of Peace, the Guardian, the Mighty, the Compeller, the Supreme. The Prophet ﷺ recited these three ayahs every morning.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 60, why_this_surah: "The surah of the examined woman (al-mumtaḥana). When Muslim women fled Makkah to Madinah, this surah established the protocol: examine their faith, and if they are sincere believers, do not return them to the disbelievers. The Quran's most specific legislation about women's asylum rights — a 7th-century refugee law.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 61, why_this_surah: "The surah of the ranks (al-ṣaff) — 'Indeed, God loves those who fight in His cause in a row as though they are a solid structure' (61:4). Contains Jesus's prophecy of Ahmad (61:6) and the image of faith as a transaction: 'Shall I direct you to a commerce that will save you from a painful punishment?' (61:10).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 62, why_this_surah: "The surah of Friday (al-Jumu'ah) — containing the command that established the weekly congregational prayer: 'When the call is made for prayer on Friday, hasten to the remembrance of God and leave trade' (62:9). The surah the Prophet ﷺ recited in the Friday prayer itself, alongside Al-Munafiqun or Al-A'la.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 63, why_this_surah: "The surah of the hypocrites (al-munāfiqūn) — the internal threat that the Quran spends more time diagnosing than the external one. 'When you see them, their forms please you; and when they speak, you listen to their speech. They are as if they were pieces of wood propped up' (63:4). Beautiful on the outside, hollow within.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 64, why_this_surah: "The surah of mutual loss and gain (al-taghābun) — the Day when some gain what others lose. Contains one of the Quran's most balanced statements about family: 'Among your spouses and your children are enemies to you, so beware of them. But if you pardon and overlook and forgive, then indeed God is Forgiving and Merciful' (64:14).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 65, why_this_surah: "The surah of divorce (al-ṭalāq) — the Quran's detailed legislation on how separation must preserve dignity. Waiting periods, housing rights, financial support, witnesses. The surah that makes the end of a marriage a matter of divine law rather than male whim. 'You do not know — perhaps God will bring about a new situation' (65:1).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 66, why_this_surah: "Opens with God addressing the Prophet ﷺ directly: 'Why do you prohibit what God has made lawful for you, seeking the approval of your wives?' A domestic incident in the Prophet's ﷺ household became revelation — the Quran showing that even the best marriage requires divine mediation. Contains Maryam and Fir'awn's wife as models of faith.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 67, why_this_surah: "The Prophet ﷺ said: 'There is a surah in the Quran of thirty ayahs that intercedes for its companion until he is forgiven — Tabārak alladhī biyadihi'l-mulk.' Muslims recite it every night before sleep as a shield from the punishment of the grave. Thirty ayahs that begin with sovereignty and end with a question: who will give you water if God withholds it?", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 68, why_this_surah: "Opens with an oath by the pen — 'Nūn. By the pen and what they inscribe.' The second revelation after Al-'Alaq, defending the Prophet ﷺ against charges of madness. Contains the parable of the garden owners who planned to harvest secretly and deny the poor — and woke to find their garden destroyed. The pen, the character, the consequence.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 69, why_this_surah: "The surah of the inevitable reality (al-ḥāqqah) — a name for the Day of Judgment that means 'the thing that must happen.' Opens with three names for the Day, then shows what happened to those who denied it: 'Ad destroyed by a screaming wind for seven nights and eight days, Thamud by a single blast. Then the scene: the earth and mountains lifted and crushed in one blow.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 70, why_this_surah: "The surah of the ascending stairways (al-ma'ārij) — 'The angels and the Spirit ascend to Him in a Day whose span is fifty thousand years' (70:4). Then the portrait of the human being: anxious when evil touches him, stingy when good touches him — except those who pray consistently. The surah that names impatience as the human default.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 71, why_this_surah: "The surah of Nuh — 950 years of calling his people to God, and they covered their ears with their garments. The most detailed account of a prophet's frustration: 'I called them publicly, I called them secretly, I said seek forgiveness and He will send rain.' The surah that shows what a millennium of patience looks like when the answer is still no.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 72, why_this_surah: "The surah where jinn overhear the Quran and believe — 'We have heard an amazing recitation. It guides to the right course, and we have believed in it' (72:1-2). The Prophet ﷺ was reciting at Nakhlah when a group of jinn listened. The surah reports their testimony, their theological debates, and their decision to submit — all from their perspective.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 73, why_this_surah: "The surah that established the night prayer — 'Stand in prayer at night, except a little. Half of it, or subtract from it a little, or add to it' (73:2-4). Revealed early, when the Prophet ﷺ needed spiritual fuel for the mission ahead. The night is when the Quran lands heaviest: 'Indeed, the hours of the night are more effective for training and more suitable for words' (73:6).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 74, why_this_surah: "The surah of the one wrapped in a cloak — the Prophet ﷺ after his first encounter with Jibril, trembling, asking Khadijah to cover him. Then the command: 'Arise and warn.' This is the moment the private experience of revelation became a public mission. The surah that turns a frightened man into a messenger.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 75, why_this_surah: "The surah of the Day of Resurrection (al-qiyāmah) — 'Does the human being think that We will not reassemble his bones? Yes, We are able to reconstruct even his fingertips' (75:3-4). The Quran's most specific claim about resurrection: God can reconstruct your unique fingerprints. The ayah that anticipated forensic science by thirteen centuries.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 76, why_this_surah: "The Prophet ﷺ recited it in the second raka'ah of Fajr every Friday, paired with As-Sajdah (32). 'Has there come upon the human being a period of time when he was nothing worth mentioning?' (76:1). The surah traces the human from non-existence through creation, testing, and ultimate destination — grateful or ungrateful.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 77, why_this_surah: "The surah of the sent winds (al-mursalāt) — its refrain 'Woe, that Day, to the deniers' repeats ten times, more than any other refrain in the Quran. Ibn Mas'ud said the Prophet ﷺ recited it to them in a cave at Mina during Hajj. The surah that makes denial feel like a physical weight through sheer repetition.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
]

async function main() {
  let success = 0
  let failed = 0

  for (const o of overhauls) {
    const { error } = await supabase
      .from('surah_visual_data')
      .update({
        why_this_surah: o.why_this_surah,
        tabs: o.tabs,
        updated_at: new Date().toISOString(),
      })
      .eq('surah_number', o.surah_number)

    if (error) {
      console.error(`✗ ${o.surah_number}: ${error.message}`)
      failed++
    } else {
      console.log(`✓ ${o.surah_number} updated (tabs: ${o.tabs.length})`)
      success++
    }
  }

  console.log(`\n${success} updated, ${failed} failed`)
}

main()
