/**
 * Batch 4b: Overhaul surahs 21-50
 * Run: npx tsx scripts/batch-visual-overhaul-4b.ts
 */
import { createClient } from '@supabase/supabase-js'
import * as dotenv from 'dotenv'

dotenv.config({ path: '.env.local' })

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!
)

const overhauls = [
  { surah_number: 21, why_this_surah: "The surah of the prophets — twenty-one named in rapid succession, each story compressed to its essential moment. Ibrahim smashing the idols, Ayyub calling out in illness, Yunus in the belly of the whale, Maryam and her son. The Quran's argument: prophecy is one continuous chain, and the message has always been the same.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 22, why_this_surah: "The surah of Hajj — the only surah named after one of the five pillars. Contains the permission to fight (22:39), the first ayah revealed allowing self-defense. Uniquely contains two prostrations of recitation. The surah bridges Makkah and Madinah, revelation and legislation, Ibrahim's ancient call and the Prophet's ﷺ living community.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 23, why_this_surah: "Opens with the qualities that define successful believers — humility in prayer, turning away from idle speech, paying zakah, guarding chastity. The Prophet ﷺ was asked 'What does success in faith look like?' This surah answers: the inner life shapes the outer, and both are being recorded.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 24, why_this_surah: "The surah of light and social law — containing the Light Verse (24:35), one of the most contemplated passages in all of Islamic philosophy. Also contains the laws of modesty, the prohibition of slander, the protocol for entering homes, and the vindication of 'A'ishah after the incident of the ifk (false accusation).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 25, why_this_surah: "Named after the Furqān — the Criterion, the ability to distinguish truth from falsehood. The surah responds to every objection the Quraysh raised against the Prophet ﷺ: why doesn't he eat like us, why wasn't an angel sent, why wasn't the Quran revealed all at once? Then closes with the qualities of 'the servants of the Most Merciful' — the most beautiful character sketch in the Quran.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 26, why_this_surah: "The longest of the Makkan surahs at 227 ayahs, built on a refrain that repeats after each prophetic story: 'Indeed in that is a sign, but most of them were not to be believers. And indeed, your Lord — He is the Mighty, the Merciful.' Seven prophets, seven rejections, one repeating chorus. The Quran as a litany.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 27, why_this_surah: "The surah of Sulayman — who understood the speech of ants, commanded the jinn, and received the throne of the Queen of Sheba before she could arrive. Contains the most detailed portrait of wise sovereignty in the Quran: power used for justice, knowledge used for humility, and a king who thanks God rather than claiming credit.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 28, why_this_surah: "The most intimate telling of Musa's story — from his birth (mother placing him in the river) through his flight to Madyan, his marriage, the burning bush, and the confrontation with Fir'awn. Then Qarun's story: the man whose wealth made him forget where it came from. The surah that pairs prophetic courage with material arrogance.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 29, why_this_surah: "Opens with 'Do people think they will be left alone because they say we believe, and they will not be tested?' The surah revealed when early Muslims were being tortured in Makkah. The spider's web (29:41) becomes the metaphor for every false shelter — the flimsiest of structures when measured against the refuge of God.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 30, why_this_surah: "Predicted the future: 'The Romans have been defeated in the nearest land, and they, after their defeat, will be victorious within a few years' (30:2-4). Revealed when Persia crushed Byzantium — and within a decade, Byzantium won. Abu Bakr wagered on it and won. The only surah in the Quran that makes a historically falsifiable prediction.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 31, why_this_surah: "The surah of a father's wisdom — Luqman advising his son. 'O my son, establish prayer, enjoin what is right, forbid what is wrong, and be patient. Do not turn your cheek in contempt toward people and do not walk through the earth exultantly.' The Quran gives a non-prophet the longest parental monologue in scripture.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 32, why_this_surah: "The Prophet ﷺ recited it every Friday morning in Fajr prayer, alongside Al-Insan (76). Thirty ayahs covering creation, revelation, resurrection — the entire arc of existence compressed. Contains the verse 'No soul knows what has been hidden for them of comfort' (32:17), describing paradise in terms of concealment rather than spectacle.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 33, why_this_surah: "The surah of the Battle of the Trench (Khandaq) — when all of Arabia's tribes besieged Madinah, and the Muslims dug a trench on Salman al-Farisi's advice. Contains the command of hijab, the marriage of Zaynab bint Jahsh, and the most concentrated passage about the Prophet ﷺ as a model: 'In the Messenger of God you have an excellent example' (33:21).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 34, why_this_surah: "Named after the ancient kingdom of Saba' (Sheba) in Yemen — a civilization blessed with gardens and irrigation, who turned away from God until a flood destroyed everything. The surah pairs Dawud and Sulayman (grateful recipients of power) against Saba' (ungrateful recipients of abundance). Gratitude and ingratitude as the fork in every civilization's road.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 35, why_this_surah: "Opens with God as the originator (Fāṭir) of the heavens and the earth, who sends angels with two, three, and four wings. The surah of origins — why things exist, why they are the way they are, why the seen world points to the unseen. 'The blind and the seeing are not alike, nor are the darkness and the light, nor the shade and the heat' (35:19-21).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 36, why_this_surah: "The Prophet ﷺ called it 'the heart of the Quran.' Muslims recite it for the dying, at funerals, and on Thursday nights. Eighty-three ayahs that compress the Quran's core arguments: a messenger sent to a heedless town, the evidence of creation, the certainty of resurrection, and the final reckoning.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 37, why_this_surah: "Opens with angels standing in rows (ṣaffāt) — a military formation of the unseen. Then moves through prophets: Nuh, Ibrahim (the knife at Isma'il's throat, the ransom), Musa, Harun, Ilyas, Lut, Yunus in the whale. The surah's refrain — 'Peace upon Nuh... Peace upon Ibrahim... Peace upon Musa and Harun' — reads like a roll call of honor.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 38, why_this_surah: "Opens with the letter Ṣād and 'the Quran full of reminder.' The surah of Dawud — his judgment between two litigants (the parable of the ewes), his repentance, and the command to judge between people with justice. Also contains the most detailed throne-room scene with Iblis, where he asks for a reprieve and God grants it.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 39, why_this_surah: "The surah of groups (zumar) — humanity arriving at the gates of Hell and the gates of Paradise in groups. Contains the verse 'Say: O My servants who have transgressed against themselves, do not despair of the mercy of God. Indeed, God forgives all sins' (39:53) — the verse of greatest hope in the entire Quran.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 40, why_this_surah: "The first of the seven Ḥā-Mīm surahs (40-46). Named Ghāfir — the Forgiver. Contains the story of the believing man from Fir'awn's family who concealed his faith and then spoke: 'Will you kill a man because he says my Lord is God?' The Quran's portrait of moral courage from inside a hostile system.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 41, why_this_surah: "When 'Utba ibn Rabi'a, a Quraysh leader, came to negotiate with the Prophet ﷺ, the Prophet recited Fussilat until 'Utba returned shaken, saying 'I have heard something the like of which I have never heard.' The surah that silenced the negotiator. Contains the verse: 'Repel evil with what is better, and the one who was your enemy becomes your closest friend' (41:34).", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 42, why_this_surah: "The surah of consultation (shūrā) — 'their affairs are conducted by mutual consultation among them' (42:38). One of the foundations of Islamic governance. Also contains the verse describing God: 'There is nothing like Him, and He is the All-Hearing, the All-Seeing' (42:11) — the Quran's most concise statement of divine incomparability.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 43, why_this_surah: "The surah of golden ornaments (zukhruf) — the decorations that dazzle and distract. When the polytheists asked why the Quran wasn't sent to a wealthy leader, this surah responded: 'Is it they who distribute the mercy of your Lord?' (43:32). Contains the Quran's most direct address about Jesus: a servant, a prophet, a sign — and the disputes about him.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 44, why_this_surah: "The surah of the smoke (dukhān) — a day when the sky brings a visible smoke. The Prophet ﷺ encouraged reciting it on Thursday nights. Contains the Quran's most compressed Exodus narrative: 'Leave the sea parted; indeed, they are an army to be drowned' (44:24). Ten ayahs do what the Torah takes chapters to describe.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 45, why_this_surah: "The surah of kneeling (jāthiya) — 'And you will see every community kneeling' (45:28). The Day when nations kneel before their records. The surah asks the hardest question about disbelief: 'Have you seen the one who takes as his god his own desire?' (45:23). Not idol worship but self-worship — the subtlest form of shirk.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 46, why_this_surah: "Named after the sand dunes (aḥqāf) of 'Ad's territory — the wind-sculpted landscape where an entire civilization vanished. The surah's central scene: a group of jinn overhear the Prophet ﷺ reciting the Quran and rush back to warn their people. Evidence that the message crosses the boundary between seen and unseen worlds.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 47, why_this_surah: "The only surah named after the Prophet Muhammad ﷺ. Revealed after the migration to Madinah, when the community had to decide: fight or submit? The surah's answer is direct — those who oppose God and His Messenger will have their deeds rendered worthless. Contains the image of paradise with rivers of water, milk, wine, and honey.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 48, why_this_surah: "The surah of victory (al-fatḥ) — revealed after the Treaty of Hudaybiyah, which the companions initially saw as a humiliation. The Prophet ﷺ called it 'a surah more beloved to me than everything under the sun.' What looked like a political loss became the opening that led to the peaceful conquest of Makkah two years later.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 49, why_this_surah: "The surah of manners (adab) — the etiquette of being Muslim in community. Don't raise your voice above the Prophet's, don't call out to him from behind the chambers, verify news before acting on it, don't mock one another, don't spy, don't backbite. Thirteen ayahs that define what it means to live with other people.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
  { surah_number: 50, why_this_surah: "The Prophet ﷺ recited Surah Qaf in every Friday khutbah until he had memorized it by heart from repetition — and recommended it to others. Opens with an oath by the Quran itself: 'Qāf. By the glorious Quran.' The surah's argument for resurrection is built entirely on botanical evidence: look at what rain does to dead earth.", tabs: [{ id: "sections", label: "Sections", diagramKey: "sectionJourney", renderer: "journey" }, { id: "ring", label: "The Ring", diagramKey: "chiasticRing", renderer: "ring" }, { id: "absent", label: "Absences", diagramKey: "absenceMap", renderer: "absence" }, { id: "text", label: "Text", renderer: "text" }] },
]

async function main() {
  let success = 0
  let failed = 0

  for (const o of overhauls) {
    const { error } = await supabase
      .from('surah_visual_data')
      .update({
        why_this_surah: o.why_this_surah,
        tabs: o.tabs,
        updated_at: new Date().toISOString(),
      })
      .eq('surah_number', o.surah_number)

    if (error) {
      console.error(`✗ ${o.surah_number}: ${error.message}`)
      failed++
    } else {
      console.log(`✓ ${o.surah_number} updated (tabs: ${o.tabs.length})`)
      success++
    }
  }

  console.log(`\n${success} updated, ${failed} failed`)
}

main()
